In [12]:
import tensorflow as tf

Interactive sesssion cho phép đưa dữ liệu vào như kiểu hàm số $f(x)$ và chạy hàm eval() ngay đằng sau như bên dưới 

In [13]:
s = tf.InteractiveSession() 
x = tf.constant([[2,3],[1,2]])
tf.transpose(x).eval() # chuyển vị

/home/thu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


array([[2, 1],
       [3, 2]], dtype=int32)

In [14]:
tf.matmul(x,x).eval() # phép nhân ma trận

array([[ 7, 12],
       [ 4,  7]], dtype=int32)

lấy nghịch đảo nhưng trước khi lấy nghịch đảo, ta phải chuyển tensor x sang định dạng float bằng ``tf.to_float``:

In [9]:
x = tf.to_float(x)
tf.matrix_inverse(x).eval() 

array([[ 2., -3.],
       [-1.,  2.]], dtype=float32)

In [11]:
tf.matrix_determinant(x).eval() # tính det

1.0

In [14]:
tf.matrix_solve(x,[[1],[2]]).eval() # giải hệ phương trình

array([[-4.],
       [ 3.]], dtype=float32)

# Reduction

để hiển thị giá trị của một tensor đã tạo trước đó:

In [18]:
x.eval()

array([[2., 3.],
       [1., 2.]], dtype=float32)

để tìm tích, trung bình, max, min, (một/tất cả các) phần tử thỏa điều kiện cho trước, ta dùng ``tf.reduce_prod/mean/max/min/any/all`` kết hợp với ``reduction_indices``là 0 cho cột, 1 cho dòng:

In [21]:
tf.reduce_prod(x,reduction_indices =0).eval()

array([2., 6.], dtype=float32)

In [22]:
tf.reduce_prod(x,reduction_indices =1).eval()

array([6., 2.], dtype=float32)

In [31]:
bool_tens = tf.constant([[True,False],[True,True]])
bool_tens.eval()

array([[ True, False],
       [ True,  True]])

In [32]:
tf.reduce_all(bool_tens,reduction_indices =0).eval()

array([ True, False])

In [33]:
tf.reduce_any(bool_tens,reduction_indices =1).eval()

array([ True,  True])

# Segmentation:

Tương tự như reduction nhưng trong qúa trình này, ta làm theo nhóm (nhóm ở đây dựa trên dòng):

- ``gr_id`` chứa group indexes, cho ta biết nhóm các dòng thuộc về

- sau đó, dùng ``tf.segment_prod/mean/max/min/any/all`` 

In [15]:
y = tf.constant([[1,2,3,4],[4,3,2,1],[0,1,1,0]])
y.eval()

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [0, 1, 1, 0]], dtype=int32)

In [10]:
# dòng 1 thuộc nhóm 0; dòng 2,3 thuộc nhóm 1
gr_id = tf.constant([0,1,1]) 
tf.segment_sum(y,gr_id).eval()

array([[1, 2, 3, 4],
       [4, 4, 3, 1]], dtype=int32)

In [11]:
tf.segment_max(y,gr_id).eval()

array([[1, 2, 3, 4],
       [4, 3, 2, 1]], dtype=int32)

# Argmin, Argmax

In [22]:
y.eval()

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [0, 1, 1, 0]], dtype=int32)

    tìm VỊ TRÍ có giá trị lớn nhất theo cột

In [27]:
tf.argmax(y,0).eval()

array([1, 1, 0, 0])

    tìm VỊ TRÍ có giá trị lớn nhất theo dòng

In [28]:
tf.argmax(y,1).eval()

array([3, 0, 1])