In [7]:
import tensorflow as tf
s = tf.InteractiveSession()

/home/thu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


# List

In [8]:
list1 = tf.constant([1,2,3,4,3,2,5])
list2 = tf.constant([1,2,3])
tf.unique(list1)[0].eval()

array([1, 2, 3, 4, 5], dtype=int32)

In [11]:
tf.setdiff1d(list1,list2)[0].eval()

array([4, 5], dtype=int32)

# đổi kích cỡ tensor:

In [12]:
y = tf.constant([[1,2,3,4],[4,3,2,1],[0,1,1,0]])
y.eval()

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [0, 1, 1, 0]], dtype=int32)

In [13]:
# rank của tensor
tf.rank(y).eval()

2

 chuyển thành ma trận cỡ $4\times 3$:

In [17]:
tf.reshape(y,[4,3]).eval()

array([[1, 2, 3],
       [4, 4, 3],
       [2, 1, 0],
       [1, 1, 0]], dtype=int32)

tăng số chiều

In [20]:
z = tf.expand_dims(y,1).eval()
z

array([[[1, 2, 3, 4]],

       [[4, 3, 2, 1]],

       [[0, 1, 1, 0]]], dtype=int32)

giảm chiều trở lại:

In [21]:
tf.squeeze(z).eval()

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [0, 1, 1, 0]], dtype=int32)

# cắt tensor:

In [46]:
y.eval()

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [0, 1, 1, 0]], dtype=int32)

In [58]:
tf.slice(y,[1,1],[2,2]).eval()

array([[3, 2],
       [1, 1]], dtype=int32)

In [36]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]],
                 [[3, 3, 3], [0, 0, 0]],
                 [[7, 7, 7], [6, 6, 6]]])
t.eval()

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [0, 0, 0]],

       [[7, 7, 7],
        [6, 6, 6]]], dtype=int32)

In [31]:
tf.slice(t, [1, 0, 0], [1, 1, 3]).eval() 

array([[[3, 3, 3]]], dtype=int32)

In [33]:
tf.slice(t, [1, 0, 0], [1, 2, 3]).eval()

array([[[3, 3, 3],
        [4, 4, 4]]], dtype=int32)

In [35]:
tf.slice(t, [1, 0, 0], [2, 1, 3]).eval()

array([[[3, 3, 3]],

       [[5, 5, 5]]], dtype=int32)

# ghép tensor

In [69]:
tf.tile([0,1],[3]).eval()

array([0, 1, 0, 1, 0, 1], dtype=int32)

In [74]:
y.eval()

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [0, 1, 1, 0]], dtype=int32)

In [73]:
tf.pad(y,[[0,1],[0,1]]).eval()

array([[1, 2, 3, 4, 0],
       [4, 3, 2, 1, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [79]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 7, 7], [5, 5, 5]]
tf.concat([t1, t2], 0).eval()  

array([[1, 2, 3],
       [4, 5, 6],
       [7, 7, 7],
       [5, 5, 5]], dtype=int32)

In [81]:
tf.concat([t1, t2], 1).eval()

array([[1, 2, 3, 7, 7, 7],
       [4, 5, 6, 5, 5, 5]], dtype=int32)

In [98]:
z = tf.stack([t1,t2]).eval()
z

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 7, 7],
        [5, 5, 5]]], dtype=int32)

In [99]:
z = s.run(tf.unstack(z))
z

[array([[1, 2, 3],
        [4, 5, 6]], dtype=int32), array([[7, 7, 7],
        [5, 5, 5]], dtype=int32)]

In [91]:
y.eval()

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [0, 1, 1, 0]], dtype=int32)

In [90]:
tf.reverse(y,[False,True]).eval()

array([[0, 1, 1, 0],
       [1, 2, 3, 4],
       [4, 3, 2, 1]], dtype=int32)